config/routes.rb
Rails.application.routes.draw do
  
  root 'frontend#index'

  namespace :admin do
    resources :welcomedata
    resources :sharevideos
    resources :snotices
    resources :scustservices
    resources :sthirdparties
    resources :smedialists
    resources :galleries
    resources :services
    resources :clients
    resources :about_mes
    resources :events
    resources :contact_infos
    resources :users
  end

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
     
  get '/about_us' => 'frontend#about_us', as: 'about_us'
  get '/gallery' => 'frontend#gallery', as: 'gallery'
  
  get '/events' => 'frontend#events', as: 'events'
  get '/events/:filter' => 'frontend#events', as: 'filter_events'
  get '/event_detail/:id' => 'frontend#event_detail', as: 'event_detail'

  get '/services' => 'frontend#services', as: 'services'
  get '/contact_us' => 'frontend#contact_us', as: 'contact_us'
  
  get '/index' => 'frontend#index', as: 'index'
  get '*path' => redirect('/')
  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/about_me.rb
class Admin::AboutMe < ActiveRecord::Base
	mount_uploader :storypic, AboutmeUploader
end

app/models/admin/client.rb
class Admin::Client < ActiveRecord::Base
	mount_uploader :clientpic, ClientUploader
end

app/models/admin/contact_info.rb
class Admin::ContactInfo < ActiveRecord::Base
end

app/models/admin/event.rb
class Admin::Event < ActiveRecord::Base
	mount_uploader :eventpic, EventUploader

end

app/models/admin/gallery.rb
class Admin::Gallery < ActiveRecord::Base
	mount_uploader :pic, GalleryUploader
end

app/models/admin/scustservice.rb
class Admin::Scustservice < ActiveRecord::Base
	belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/models/admin/service.rb
class Admin::Service < ActiveRecord::Base
	has_many :admin_smedialists, :dependent => :destroy, class_name: "Admin::Smedialist"
	accepts_nested_attributes_for :admin_smedialists, :reject_if => :all_blank, :allow_destroy => true

	has_many :admin_sthirdparties, :dependent => :destroy, class_name: "Admin::Sthirdparty"
	accepts_nested_attributes_for :admin_sthirdparties, :reject_if => :all_blank, :allow_destroy => true

	has_many :admin_scustservices, :dependent => :destroy, class_name: "Admin::Scustservice"
	accepts_nested_attributes_for :admin_scustservices, :reject_if => :all_blank, :allow_destroy => true

	has_many :admin_snotices, :dependent => :destroy, class_name: "Admin::Snotice"
	accepts_nested_attributes_for :admin_snotices, :reject_if => :all_blank, :allow_destroy => true
end

app/models/admin/sharevideo.rb
class Admin::Sharevideo < ActiveRecord::Base
end

app/models/admin/smedialist.rb
class Admin::Smedialist < ActiveRecord::Base
  belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/models/admin/snotice.rb
class Admin::Snotice < ActiveRecord::Base
	belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/models/admin/sthirdparty.rb
class Admin::Sthirdparty < ActiveRecord::Base
	mount_uploader :tppic, ThirdpartyUploader
	belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/models/admin/welcomedatum.rb
class Admin::Welcomedatum < ActiveRecord::Base
	mount_uploader :picture, WelcomepicUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  layout :layout_by_resource
  
  protected
  
  def layout_by_resource
    if devise_controller?
      if ["users","contact_infos"].include?(params[:controller])
        "admin/admin"
      else
        # this layout will be displayed on login page,forgot password, new user registration
        "admin/empty"
      end
    elsif params[:controller] == 'frontend'
      "application"
    else
      "admin/admin"
    end
  end
  
  def redirect_to_loggedin_page
    if user_signed_in?
      redirect_to admin_users_path
    end
  end

  def footer_data
    @admin_contact_infos = Admin::ContactInfo.all
  end
  
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  skip_before_filter :authenticate_user!
  before_action :redirect_to_loggedin_page
  before_action :footer_data
  
  def index 
    @events = Admin::Event.where('event_date_from >= (?)', Date.new(Time.now.year,1).beginning_of_month).limit(3)
    @prev_events = Admin::Event.where('event_date_from < (?)', Date.new(Time.now.year,1).beginning_of_month).limit(3)    

    @clients = Admin::Client.all
    @articlecount = 0
    @clients.count.times do |i|
      if i%3 == 0
        @articlecount = @articlecount+1
      end
    end

    @admin_welcomedata = Admin::Welcomedatum.all
    
    @admin_sharevideos = Admin::Sharevideo.all

  end
  
  def about_us
    @about_mes = Admin::AboutMe.all
    @clients = Admin::Client.all
  end
  
  def contact_us
    @admin_contact_infos = Admin::ContactInfo.all
  end
  
  def services
    @services = Admin::Service.all
  end
  
  def events
    if params[:filter] == 'current'
      @events = Admin::Event.where('event_date_from = (?) or event_date_from <= (?) and event_date_to >= (?)', Date.today, Date.today, Date.today).order(:event_date_from)
      @title = 'current'
    elsif params[:filter] == 'upcoming'
      @events = Admin::Event.where('event_date_from > (?)', Date.today).order(:event_date_from)
      @title = 'upcoming'
    elsif params[:filter] == 'past'
      @events = Admin::Event.where('event_date_to < (?)', Date.today).order(:event_date_to)
      @title = 'past'
    else
      @events = Admin::Event.all
      @title = 'all'
    end
  end

  def event_detail
    @event = Admin::Event.find(params[:id])
  end
  
  def gallery
    @admin_galleries = Admin::Gallery.all
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    render :layout => "admin/empty"
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name)
      params[:controller] == controller_name ? (controller_name == "frontend" ? "act":"active") : nil
  end

  def is_active_action(action_name)
      params[:action] == action_name ? (controller_name == "frontend" ? "act":"active") : nil
  end

  def is_active_controller_action(controller_name, action_name)
		params[:controller] == controller_name && params[:action] == action_name ? (controller_name == "frontend" ? "act":"active") : nil
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/admin/_breadcrumb.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Breadcrumb</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'users', :action => 'index' %>">Dashboard</a>
            </li>
            <li>
                <%= params[:controller].split("/").map{|s| s.humanize}.map(&:inspect).join("</li><li>").gsub(/"/, '').html_safe rescue nil%>
            </li>
            <li class="active">
                <strong><%= params[:action].humanize %></strong>
            </li>
        </ol>
    </div>
</div>

app/views/layouts/admin/_flash_msg.html.erb
<br>
<% if notice %>
  <p class="alert alert-success alert-dismissable">
  	<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  	<%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger alert-dismissable">
  	<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  	<%= alert %>
  </p>
<% end %>

app/views/layouts/admin/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        <a href="http://www.bhavishy.com" target="_blank">bhavishy.com</a>
    </div>
    <div>
        <strong>Copyright</strong> Bhavishy Technologies &copy; 2015-2016
    </div>
</div>

app/views/layouts/admin/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="<%= image_url 'small_pic.JPG' %>"/>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Chitresh Goyal</strong>
                            </span> <span class="text-muted text-xs block">Owner <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li>
                        	<%= link_to 'Edit profile', edit_user_registration_path %>
                        </li>
                        <!-- <li><a href="">Contacts</a>
                        </li>
                        <li><a href="">Mailbox</a>
                        </li> -->
                        <li class="divider"></li>
                        <li><%= link_to "Logout", destroy_user_session_path %></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>

            <li class="<%= is_active_controller('admin/welcomedata') || is_active_controller('admin/sharevideos') %>">
                <a href="#">
                    <i class="fa fa-align-center"></i> 
                    <span class="nav-label">Index</span> 
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/welcomedata') || is_active_controller('admin/sharevideos') %>" >
                    <li class="<%= is_active_controller('admin/welcomedata') %>">
                            <a href="#">
                                Welcome
                                <!-- <span class="nav-label">Welcome</span>  -->
                                <span class="fa arrow"></span>
                            </a>
                        <ul class="nav nav-third-level <%= is_active_controller('admin/welcomedata') %> ">
                            <li class="<%= is_active_controller_action('admin/welcomedata','index') %>">
                                <%= link_to "List", admin_welcomedata_path %></li>
                            <li class="<%= is_active_controller_action('admin/welcomedata','new') %>">
                                <%= link_to "New", new_admin_welcomedatum_path %></li>
                        </ul>
                    </li>
                    <li class="<%= is_active_controller('admin/sharevideos') %>">
                            <a href="#">
                                Videos
                                <!-- <span class="nav-label">Videos</span>  -->
                                <span class="fa arrow"></span>
                            </a>
                        <ul class="nav nav-third-level <%= is_active_controller('admin/sharevideos') %> ">
                            <li class="<%= is_active_controller_action('admin/sharevideos','index') %>">
                                <%= link_to "List", admin_sharevideos_path %></li>
                            <li class="<%= is_active_controller_action('admin/sharevideos','new') %>">
                                <%= link_to "New", new_admin_sharevideo_path %></li>
                        </ul>
                    </li>
                </ul>
            </li>

            <li class="<%= is_active_controller('admin/about_mes') || is_active_controller('admin/clients') %>">
                <a href="#">
                    <i class="fa fa-th-large"></i> 
                    <span class="nav-label">About Us</span> 
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/about_mes') || is_active_controller('admin/clients')%>">
                    <li class="<%= is_active_controller_action('admin/about_mes','index') %>">
                        <%= link_to "Configuration", admin_about_mes_path %></li>
                    <li class="<%= is_active_controller_action('admin/about_mes','new') %>">
                        <%= link_to "New Configuration", new_admin_about_me_path %></li>
                    
                    <li class="<%= is_active_controller('admin/clients') %>">
                        <a href="#">
                            Client Details
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-third-level <%= is_active_controller('admin/clients') %>">    
                            <li class="<%= is_active_controller_action('admin/clients','index') %>"><%= link_to "List", admin_clients_path %></li>
                            <li class="<%= is_active_controller_action('admin/clients','new') %>"><%= link_to "New Client", new_admin_client_path %></li>        
                        </ul>
                    </li>
                </ul>
            </li>

            <li class="<%= is_active_controller('admin/services') %>">
                <a href="#">
                    <i class="fa fa-wrench"></i> 
                    <span class="nav-label">Services</span> 
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/services') %> ">
                    <li class="<%= is_active_controller_action('admin/services','index') %>">
                        <%= link_to "Configuration", admin_services_path %></li>
                    <li class="<%= is_active_controller_action('admin/services','new') %>">
                        <%= link_to "New Configuration", new_admin_service_path %></li>
                </ul>
            </li>
            
            <li class="<%= is_active_controller('admin/events') %>">
                <a href="#">
                    <i class="fa fa-calendar"></i> 
                    <span class="nav-label">Events</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/events')%>">
                    <li class="<%= is_active_controller_action('admin/events','index') %>">
                        <%= link_to "List", admin_events_path %></li>
                    <li class="<%= is_active_controller_action('admin/events','new') %>">
                        <%= link_to "New", new_admin_event_path %></li>
                </ul>
            </li>

            <li class="<%= is_active_controller('admin/galleries') %>">
                <a href="#">
                    <i class="fa fa-picture-o"></i> 
                    <span class="nav-label">Gallery</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/galleries')%>">
                    <li class="<%= is_active_controller_action('admin/galleries','index') %>">
                        <%= link_to "List Images", admin_galleries_path %></li>
                    <li class="<%= is_active_controller_action('admin/galleries','new') %>">
                        <%= link_to "Upload Image", new_admin_gallery_path %></li>
                </ul>
            </li>

            <li class="<%= is_active_controller('admin/contact_infos') %>">
                <a href="#"><i class="fa fa-phone"></i> <span class="nav-label">
                	Contact us</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level <%= is_active_controller('admin/contact_infos')%>">
                    <li class="<%= is_active_controller_action('admin/contact_infos','index') %>"><%= link_to "List", admin_contact_infos_path %></li>
                    <li class="<%= is_active_controller_action('admin/contact_infos','new') %>"><%= link_to "New", new_admin_contact_info_path %></li>
                </ul>
            </li>

            
            
            <!-- <li>
                    <a href="#">
                        <i class="fa fa-sitemap"></i> 
                        <span class="nav-label">Menu Levels </span>
                        <span class="fa arrow"></span>
                    </a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>

                        </ul>
                    </li>
                    <li><a href="#">Second Level Item</a></li>
                    <li>
                        <a href="#">Second Level Item</a></li>
                    <li>
                        <a href="#">Second Level Item</a></li>
                </ul>
            </li> -->
        </ul>

    </div>
</nav>

app/views/layouts/admin/_skinconfig.html.erb
<div class="theme-config">
    <div class="theme-config-box">
        <div class="spin-icon">
            <i class="fa fa-cogs fa-spin"></i>
        </div>
        <div class="skin-setttings">
            <div class="title">Configuration</div>
            <div class="setings-item">
                <span>
                    Collapse menu
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="collapsemenu">
                        <label class="onoffswitch-label" for="collapsemenu">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed sidebar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedsidebar" class="onoffswitch-checkbox" id="fixedsidebar">
                        <label class="onoffswitch-label" for="fixedsidebar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Top navbar
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixednavbar" class="onoffswitch-checkbox" id="fixednavbar">
                        <label class="onoffswitch-label" for="fixednavbar">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Boxed layout
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="boxedlayout" class="onoffswitch-checkbox" id="boxedlayout">
                        <label class="onoffswitch-label" for="boxedlayout">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="setings-item">
                <span>
                    Fixed footer
                </span>

                <div class="switch">
                    <div class="onoffswitch">
                        <input type="checkbox" name="fixedfooter" class="onoffswitch-checkbox" id="fixedfooter">
                        <label class="onoffswitch-label" for="fixedfooter">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="title">Skins</div>
            <div class="setings-item default-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-0">
                        Default
                    </a>
                </span>
            </div>
            <div class="setings-item blue-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-1">
                        Blue light
                    </a>
                </span>
            </div>
            <div class="setings-item yellow-skin">
                <span class="skin-name ">
                    <a href="#" class="s-skin-3">
                        Yellow/Purple
                    </a>
                </span>
            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">
    // Config box

    // Enable/disable fixed top navbar
    $('#fixednavbar').click(function () {
        if ($('#fixednavbar').is(':checked')) {
            $(".navbar-static-top").removeClass('navbar-static-top').addClass('navbar-fixed-top');
            $("body").removeClass('boxed-layout');
            $("body").addClass('fixed-nav');
            $('#boxedlayout').prop('checked', false);

            if (localStorageSupport) {
                localStorage.setItem("boxedlayout",'off');
            }

            if (localStorageSupport) {
                localStorage.setItem("fixednavbar",'on');
            }
        } else {
            $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
            $("body").removeClass('fixed-nav');

            if (localStorageSupport) {
                localStorage.setItem("fixednavbar",'off');
            }
        }
    });

    // Enable/disable fixed sidebar
    $('#fixedsidebar').click(function () {
        if ($('#fixedsidebar').is(':checked')) {
            $("body").addClass('fixed-sidebar');
            $('.sidebar-collapse').slimScroll({
                height: '100%',
                railOpacity: 0.9
            });

            if (localStorageSupport) {
                localStorage.setItem("fixedsidebar",'on');
            }
        } else {
            $('.sidebar-collapse').slimscroll({destroy: true});
            $('.sidebar-collapse').attr('style', '');
            $("body").removeClass('fixed-sidebar');

            if (localStorageSupport) {
                localStorage.setItem("fixedsidebar",'off');
            }
        }
    });

    // Enable/disable collapse menu
    $('#collapsemenu').click(function () {
        if ($('#collapsemenu').is(':checked')) {
            $("body").addClass('mini-navbar');
            SmoothlyMenu();

            if (localStorageSupport) {
                localStorage.setItem("collapse_menu",'on');
            }

        } else {
            $("body").removeClass('mini-navbar');
            SmoothlyMenu();

            if (localStorageSupport) {
                localStorage.setItem("collapse_menu",'off');
            }
        }
    });

    // Enable/disable boxed layout
    $('#boxedlayout').click(function () {
        if ($('#boxedlayout').is(':checked')) {
            $("body").addClass('boxed-layout');
            $('#fixednavbar').prop('checked', false);
            $(".navbar-fixed-top").removeClass('navbar-fixed-top').addClass('navbar-static-top');
            $("body").removeClass('fixed-nav');
            $(".footer").removeClass('fixed');
            $('#fixedfooter').prop('checked', false);

            if (localStorageSupport) {
                localStorage.setItem("fixednavbar",'off');
            }

            if (localStorageSupport) {
                localStorage.setItem("fixedfooter",'off');
            }


            if (localStorageSupport) {
                localStorage.setItem("boxedlayout",'on');
            }
        } else {
            $("body").removeClass('boxed-layout');

            if (localStorageSupport) {
                localStorage.setItem("boxedlayout",'off');
            }
        }
    });

    // Enable/disable fixed footer
    $('#fixedfooter').click(function () {
        if ($('#fixedfooter').is(':checked')) {
            $('#boxedlayout').prop('checked', false);
            $("body").removeClass('boxed-layout');
            $(".footer").addClass('fixed');

            if (localStorageSupport) {
                localStorage.setItem("boxedlayout",'off');
            }

            if (localStorageSupport) {
                localStorage.setItem("fixedfooter",'on');
            }
        } else {
            $(".footer").removeClass('fixed');

            if (localStorageSupport) {
                localStorage.setItem("fixedfooter",'off');
            }
        }
    });

    // SKIN Select
    $('.spin-icon').click(function () {
        $(".theme-config-box").toggleClass("show");
    });

    // Default skin
    $('.s-skin-0').click(function () {
        $("body").removeClass("skin-1");
        $("body").removeClass("skin-2");
        $("body").removeClass("skin-3");
    });

    // Blue skin
    $('.s-skin-1').click(function () {
        $("body").removeClass("skin-2");
        $("body").removeClass("skin-3");
        $("body").addClass("skin-1");
    });

    // Inspinia ultra skin
    $('.s-skin-2').click(function () {
        $("body").removeClass("skin-1");
        $("body").removeClass("skin-3");
        $("body").addClass("skin-2");
    });

    // Yellow skin
    $('.s-skin-3').click(function () {
        $("body").removeClass("skin-1");
        $("body").removeClass("skin-2");
        $("body").addClass("skin-3");
    });

    if (localStorageSupport) {
        var collapse = localStorage.getItem("collapse_menu");
        var fixedsidebar = localStorage.getItem("fixedsidebar");
        var fixednavbar = localStorage.getItem("fixednavbar");
        var boxedlayout = localStorage.getItem("boxedlayout");
        var fixedfooter = localStorage.getItem("fixedfooter");

        if (collapse == 'on') {
            $('#collapsemenu').prop('checked','checked')
        }
        if (fixedsidebar == 'on') {
            $('#fixedsidebar').prop('checked','checked')
        }
        if (fixednavbar == 'on') {
            $('#fixednavbar').prop('checked','checked')
        }
        if (boxedlayout == 'on') {
            $('#boxedlayout').prop('checked','checked')
        }
        if (fixedfooter == 'on') {
            $('#fixedfooter').prop('checked','checked')
        }
    }

</script>

<% end %>

app/views/layouts/admin/_topnavbar_2.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <i class="fa fa-reorder"></i>
        </button>
        <a href="#" class="navbar-brand">Inspinia</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a aria-expanded="false" role="button" href="<%= url_for :controller => 'layoutsoptions', :action => 'index' %>"> Back to main Layout page</a>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
                <li><a href="">Menu item</a></li>
            </ul>
        </li>

    </ul>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="#">
                <i class="fa fa-sign-out"></i> Log out
            </a>
        </li>
    </ul>
</div>
        </nav>
        </div>