config/routes.rb
Rails.application.routes.draw do
  
  root 'frontend#index'

  namespace :admin do
    resources :welcomedata
    resources :sharevideos
    resources :snotices
    resources :scustservices
    resources :sthirdparties
    resources :smedialists
    resources :galleries
    resources :services
    resources :clients
    resources :about_mes
    resources :events
    resources :contact_infos
    resources :users
  end

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
     
  get '/about_us' => 'frontend#about_us', as: 'about_us'
  get '/gallery' => 'frontend#gallery', as: 'gallery'
  
  get '/events' => 'frontend#events', as: 'events'
  get '/events/:filter' => 'frontend#events', as: 'filter_events'
  get '/event_detail/:id' => 'frontend#event_detail', as: 'event_detail'

  get '/services' => 'frontend#services', as: 'services'
  get '/contact_us' => 'frontend#contact_us', as: 'contact_us'
  
  get '/index' => 'frontend#index', as: 'index'
  get '*path' => redirect('/')
  

end

app/models/admin/sthirdparty.rb
class Admin::Sthirdparty < ActiveRecord::Base
	mount_uploader :tppic, ThirdpartyUploader
	belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/controllers/admin/sthirdparties_controller.rb
class Admin::SthirdpartiesController < ApplicationController
  before_action :set_admin_sthirdparty, only: [:show, :edit, :update, :destroy]

  # GET /admin/sthirdparties
  # GET /admin/sthirdparties.json
  def index
    @admin_sthirdparties = Admin::Sthirdparty.all
  end

  # GET /admin/sthirdparties/1
  # GET /admin/sthirdparties/1.json
  def show
  end

  # GET /admin/sthirdparties/new
  def new
    @admin_sthirdparty = Admin::Sthirdparty.new
  end

  # GET /admin/sthirdparties/1/edit
  def edit
  end

  # POST /admin/sthirdparties
  # POST /admin/sthirdparties.json
  def create
    @admin_sthirdparty = Admin::Sthirdparty.new(admin_sthirdparty_params)

    respond_to do |format|
      if @admin_sthirdparty.save
        format.html { redirect_to @admin_sthirdparty, notice: 'Sthirdparty was successfully created.' }
        format.json { render :show, status: :created, location: @admin_sthirdparty }
      else
        format.html { render :new }
        format.json { render json: @admin_sthirdparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sthirdparties/1
  # PATCH/PUT /admin/sthirdparties/1.json
  def update
    respond_to do |format|
      if @admin_sthirdparty.update(admin_sthirdparty_params)
        format.html { redirect_to @admin_sthirdparty, notice: 'Sthirdparty was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_sthirdparty }
      else
        format.html { render :edit }
        format.json { render json: @admin_sthirdparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sthirdparties/1
  # DELETE /admin/sthirdparties/1.json
  def destroy
    @admin_sthirdparty.destroy
    respond_to do |format|
      format.html { redirect_to admin_sthirdparties_url, notice: 'Sthirdparty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_sthirdparty
      @admin_sthirdparty = Admin::Sthirdparty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_sthirdparty_params
      params.require(:admin_sthirdparty).permit(:tppic, :title, :description, :service_id)
    end
end

app/helpers/admin/sthirdparties_helper.rb
module Admin::SthirdpartiesHelper
end

app/views/admin/sthirdparties/_form.html.erb
<%= form_for(@admin_sthirdparty) do |f| %>
  <% if @admin_sthirdparty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_sthirdparty.errors.count, "error") %> prohibited this admin_sthirdparty from being saved:</h2>

      <ul>
      <% @admin_sthirdparty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tppic %><br>
    <%= f.text_field :tppic %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.number_field :service_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/sthirdparties/edit.html.erb
<h1>Editing Admin Sthirdparty</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_sthirdparty %> |
<%= link_to 'Back', admin_sthirdparties_path %>

app/views/admin/sthirdparties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Sthirdparties</h1>

<table>
  <thead>
    <tr>
      <th>Tppic</th>
      <th>Title</th>
      <th>Description</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_sthirdparties.each do |admin_sthirdparty| %>
      <tr>
        <td><%= admin_sthirdparty.tppic %></td>
        <td><%= admin_sthirdparty.title %></td>
        <td><%= admin_sthirdparty.description %></td>
        <td><%= admin_sthirdparty.service_id %></td>
        <td><%= link_to 'Show', admin_sthirdparty %></td>
        <td><%= link_to 'Edit', edit_admin_sthirdparty_path(admin_sthirdparty) %></td>
        <td><%= link_to 'Destroy', admin_sthirdparty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sthirdparty', new_admin_sthirdparty_path %>

app/views/admin/sthirdparties/new.html.erb
<h1>New Admin Sthirdparty</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sthirdparties_path %>

app/views/admin/sthirdparties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tppic:</strong>
  <%= @admin_sthirdparty.tppic %>
</p>

<p>
  <strong>Title:</strong>
  <%= @admin_sthirdparty.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_sthirdparty.description %>
</p>

<p>
  <strong>Service:</strong>
  <%= @admin_sthirdparty.service_id %>
</p>

<%= link_to 'Edit', edit_admin_sthirdparty_path(@admin_sthirdparty) %> |
<%= link_to 'Back', admin_sthirdparties_path %>