config/routes.rb
Rails.application.routes.draw do
  
  root 'frontend#index'

  namespace :admin do
    resources :welcomedata
    resources :sharevideos
    resources :snotices
    resources :scustservices
    resources :sthirdparties
    resources :smedialists
    resources :galleries
    resources :services
    resources :clients
    resources :about_mes
    resources :events
    resources :contact_infos
    resources :users
  end

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
     
  get '/about_us' => 'frontend#about_us', as: 'about_us'
  get '/gallery' => 'frontend#gallery', as: 'gallery'
  
  get '/events' => 'frontend#events', as: 'events'
  get '/events/:filter' => 'frontend#events', as: 'filter_events'
  get '/event_detail/:id' => 'frontend#event_detail', as: 'event_detail'

  get '/services' => 'frontend#services', as: 'services'
  get '/contact_us' => 'frontend#contact_us', as: 'contact_us'
  
  get '/index' => 'frontend#index', as: 'index'
  get '*path' => redirect('/')
  

end

app/models/admin/smedialist.rb
class Admin::Smedialist < ActiveRecord::Base
  belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/controllers/admin/smedialists_controller.rb
class Admin::SmedialistsController < ApplicationController
  before_action :set_admin_smedialist, only: [:show, :edit, :update, :destroy]

  # GET /admin/smedialists
  # GET /admin/smedialists.json
  def index
    @admin_smedialists = Admin::Smedialist.all
  end

  # GET /admin/smedialists/1
  # GET /admin/smedialists/1.json
  def show
  end

  # GET /admin/smedialists/new
  def new
    @admin_smedialist = Admin::Smedialist.new
  end

  # GET /admin/smedialists/1/edit
  def edit
  end

  # POST /admin/smedialists
  # POST /admin/smedialists.json
  def create
    @admin_smedialist = Admin::Smedialist.new(admin_smedialist_params)

    respond_to do |format|
      if @admin_smedialist.save
        format.html { redirect_to @admin_smedialist, notice: 'Smedialist was successfully created.' }
        format.json { render :show, status: :created, location: @admin_smedialist }
      else
        format.html { render :new }
        format.json { render json: @admin_smedialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/smedialists/1
  # PATCH/PUT /admin/smedialists/1.json
  def update
    respond_to do |format|
      if @admin_smedialist.update(admin_smedialist_params)
        format.html { redirect_to @admin_smedialist, notice: 'Smedialist was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_smedialist }
      else
        format.html { render :edit }
        format.json { render json: @admin_smedialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/smedialists/1
  # DELETE /admin/smedialists/1.json
  def destroy
    @admin_smedialist.destroy
    respond_to do |format|
      format.html { redirect_to admin_smedialists_url, notice: 'Smedialist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_smedialist
      @admin_smedialist = Admin::Smedialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_smedialist_params
      params.require(:admin_smedialist).permit(:id, :title, :description, :service_id)
    end
end

app/helpers/admin/smedialists_helper.rb
module Admin::SmedialistsHelper
end

app/views/admin/smedialists/_form.html.erb
<%= form_for(@admin_smedialist) do |f| %>
  <% if @admin_smedialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_smedialist.errors.count, "error") %> prohibited this admin_smedialist from being saved:</h2>

      <ul>
      <% @admin_smedialist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :admin_service_id %><br>
    <%= f.text_field :admin_service_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/smedialists/edit.html.erb
<h1>Editing Admin Smedialist</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_smedialist %> |
<%= link_to 'Back', admin_smedialists_path %>

app/views/admin/smedialists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Smedialists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Admin service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_smedialists.each do |admin_smedialist| %>
      <tr>
        <td><%= admin_smedialist.title %></td>
        <td><%= admin_smedialist.description %></td>
        <td><%= admin_smedialist.admin_service %></td>
        <td><%= link_to 'Show', admin_smedialist %></td>
        <td><%= link_to 'Edit', edit_admin_smedialist_path(admin_smedialist) %></td>
        <td><%= link_to 'Destroy', admin_smedialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Smedialist', new_admin_smedialist_path %>

app/views/admin/smedialists/new.html.erb
<h1>New Admin Smedialist</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_smedialists_path %>

app/views/admin/smedialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_smedialist.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_smedialist.description %>
</p>

<p>
  <strong>Admin service:</strong>
  <%= @admin_smedialist.admin_service %>
</p>

<%= link_to 'Edit', edit_admin_smedialist_path(@admin_smedialist) %> |
<%= link_to 'Back', admin_smedialists_path %>