config/routes.rb
Rails.application.routes.draw do
  
  root 'frontend#index'

  namespace :admin do
    resources :welcomedata
    resources :sharevideos
    resources :snotices
    resources :scustservices
    resources :sthirdparties
    resources :smedialists
    resources :galleries
    resources :services
    resources :clients
    resources :about_mes
    resources :events
    resources :contact_infos
    resources :users
  end

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
     
  get '/about_us' => 'frontend#about_us', as: 'about_us'
  get '/gallery' => 'frontend#gallery', as: 'gallery'
  
  get '/events' => 'frontend#events', as: 'events'
  get '/events/:filter' => 'frontend#events', as: 'filter_events'
  get '/event_detail/:id' => 'frontend#event_detail', as: 'event_detail'

  get '/services' => 'frontend#services', as: 'services'
  get '/contact_us' => 'frontend#contact_us', as: 'contact_us'
  
  get '/index' => 'frontend#index', as: 'index'
  get '*path' => redirect('/')
  

end

app/models/admin/snotice.rb
class Admin::Snotice < ActiveRecord::Base
	belongs_to :admin_service, class_name: "Admin::Service", foreign_key: 'service_id'
end

app/controllers/admin/snotices_controller.rb
class Admin::SnoticesController < ApplicationController
  before_action :set_admin_snotice, only: [:show, :edit, :update, :destroy]

  # GET /admin/snotices
  # GET /admin/snotices.json
  def index
    @admin_snotices = Admin::Snotice.all
  end

  # GET /admin/snotices/1
  # GET /admin/snotices/1.json
  def show
  end

  # GET /admin/snotices/new
  def new
    @admin_snotice = Admin::Snotice.new
  end

  # GET /admin/snotices/1/edit
  def edit
  end

  # POST /admin/snotices
  # POST /admin/snotices.json
  def create
    @admin_snotice = Admin::Snotice.new(admin_snotice_params)

    respond_to do |format|
      if @admin_snotice.save
        format.html { redirect_to @admin_snotice, notice: 'Snotice was successfully created.' }
        format.json { render :show, status: :created, location: @admin_snotice }
      else
        format.html { render :new }
        format.json { render json: @admin_snotice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/snotices/1
  # PATCH/PUT /admin/snotices/1.json
  def update
    respond_to do |format|
      if @admin_snotice.update(admin_snotice_params)
        format.html { redirect_to @admin_snotice, notice: 'Snotice was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_snotice }
      else
        format.html { render :edit }
        format.json { render json: @admin_snotice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/snotices/1
  # DELETE /admin/snotices/1.json
  def destroy
    @admin_snotice.destroy
    respond_to do |format|
      format.html { redirect_to admin_snotices_url, notice: 'Snotice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_snotice
      @admin_snotice = Admin::Snotice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_snotice_params
      params.require(:admin_snotice).permit(:description, :service_id)
    end
end

app/helpers/admin/snotices_helper.rb
module Admin::SnoticesHelper
end

app/views/admin/snotices/_form.html.erb
<%= form_for(@admin_snotice) do |f| %>
  <% if @admin_snotice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_snotice.errors.count, "error") %> prohibited this admin_snotice from being saved:</h2>

      <ul>
      <% @admin_snotice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.number_field :service_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/snotices/edit.html.erb
<h1>Editing Admin Snotice</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_snotice %> |
<%= link_to 'Back', admin_snotices_path %>

app/views/admin/snotices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Snotices</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_snotices.each do |admin_snotice| %>
      <tr>
        <td><%= admin_snotice.description %></td>
        <td><%= admin_snotice.service_id %></td>
        <td><%= link_to 'Show', admin_snotice %></td>
        <td><%= link_to 'Edit', edit_admin_snotice_path(admin_snotice) %></td>
        <td><%= link_to 'Destroy', admin_snotice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snotice', new_admin_snotice_path %>

app/views/admin/snotices/new.html.erb
<h1>New Admin Snotice</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_snotices_path %>

app/views/admin/snotices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @admin_snotice.description %>
</p>

<p>
  <strong>Service:</strong>
  <%= @admin_snotice.service_id %>
</p>

<%= link_to 'Edit', edit_admin_snotice_path(@admin_snotice) %> |
<%= link_to 'Back', admin_snotices_path %>